import assert from 'node:assert/strict';
import test from 'node:test';

const saved={...process.env}; const originalFetch=globalThis.fetch;
const business='11111111-1111-4111-8111-111111111111'; const user='22222222-2222-4222-8222-222222222222'; const generation='33333333-3333-4333-8333-333333333333';
const reply=(body,ok=true,status=ok?200:500)=>({ok,status,text:async()=>typeof body==='string'?body:JSON.stringify(body),json:async()=>body});
const res=()=>({statusCode:0,body:null,headers:{},status(code){this.statusCode=code;return this;},json(body){this.body=body;return this;},setHeader(k,v){this.headers[k]=v;}});
const generated={id:generation,business_id:business,content_type:'social_post',platform:'facebook',tone:'friendly',request_text:'Test',extra_instructions:'',status:'completed',output:{main_copy:'Draft',short_alternative:'Short',call_to_action:'Call',hashtags:['#Test'],missing_information:[]},edited_output:null,approval_status:'draft',approved_at:null,created_at:new Date().toISOString(),updated_at:new Date().toISOString(),completed_at:new Date().toISOString()};
function env(){Object.assign(process.env,{TENANCY_AUTH_ENABLED:'true',SUPABASE_URL:'https://example.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'server',OPENAI_API_KEY:'fake'});}
function authMock(role='owner',writes=[]){return async(url,options={})=>{const href=String(url); if(href.endsWith('/auth/v1/user'))return reply({id:user}); if(href.includes('business_memberships'))return reply([{business_id:business,role}]); if(href.includes('business_feature_entitlements'))return reply([{feature_key:'ai_marketing',status:'active',source:'manual',expires_at:null}]); if(href.includes('marketing_generations')&&(!options.method||options.method==='GET'))return reply([generated]); if(href.includes('marketing_generations')&&options.method==='PATCH'){writes.push(JSON.parse(options.body));return reply({},true,204);} if(href.includes('business_audit_events'))return reply({},true,201); return reply({},false);};}

test('editing a saved Marketing draft resets approval and preserves tenant scope',async()=>{env();const writes=[];globalThis.fetch=authMock('admin',writes);const handler=(await import(new URL(`../lib/marketing-handler.js?edit=${Math.random()}`,import.meta.url))).default;const out=res();await handler({method:'PATCH',headers:{authorization:'Bearer x'},query:{},body:{action:'edit',generation_id:generation,output:{...generated.output,main_copy:'Edited'}}},out);assert.equal(out.statusCode,200);assert.equal(writes[0].approval_status,'draft');assert.equal(writes[0].approved_at,null);assert.equal(writes[0].approved_by,null);assert.equal(writes[0].edited_output.main_copy,'Edited');});

test('only the owner can approve Marketing content for publishing',async()=>{env();globalThis.fetch=authMock('admin',[]);let handler=(await import(new URL(`../lib/marketing-handler.js?approveadmin=${Math.random()}`,import.meta.url))).default;let out=res();await handler({method:'PATCH',headers:{authorization:'Bearer x'},query:{},body:{action:'approve',generation_id:generation}},out);assert.equal(out.statusCode,403);const writes=[];globalThis.fetch=authMock('owner',writes);handler=(await import(new URL(`../lib/marketing-handler.js?approveowner=${Math.random()}`,import.meta.url))).default;out=res();await handler({method:'PATCH',headers:{authorization:'Bearer x'},query:{},body:{action:'approve',generation_id:generation}},out);assert.equal(out.statusCode,200);assert.equal(writes[0].approval_status,'approved');assert.equal(writes[0].approved_by,user);});

test('Marketing scheduler requires a strong bearer secret before claiming jobs',async()=>{process.env.MARKETING_SCHEDULER_SECRET='s'.repeat(40);process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_SERVICE_ROLE_KEY='server';let called=false;globalThis.fetch=async()=>{called=true;return reply([]);};const handler=(await import(new URL(`../lib/marketing-scheduler-handler.js?auth=${Math.random()}`,import.meta.url))).default;let out=res();await handler({method:'POST',headers:{authorization:'Bearer wrong'}},out);assert.equal(out.statusCode,401);assert.equal(called,false);out=res();await handler({method:'POST',headers:{authorization:`Bearer ${'s'.repeat(40)}`}},out);assert.equal(out.statusCode,200);assert.equal(out.body.processed,0);assert.equal(called,true);});

test.after(()=>{for(const key of Object.keys(process.env))if(!(key in saved))delete process.env[key];Object.assign(process.env,saved);globalThis.fetch=originalFetch;});
