import { requireAuthenticatedUser, requireBusinessMember, sendAuthError } from "./auth.js";
import { recordAuditEvent } from "./audit.js";
import { assertStaffSeatAvailable } from "./billing.js";

const url = process.env.SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
const uuid = (value) => typeof value === "string" && /^[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}$/i.test(value) ? value : null;
const email = (value) => typeof value === "string" && value.length <= 320 && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.trim()) ? value.trim().toLowerCase() : null;
function parse(value) { try { const body = typeof value === "string" ? JSON.parse(value) : value || {}; return body && typeof body === "object" && !Array.isArray(body) ? body : null; } catch { return null; } }
async function request(path, options = {}) { if (!url || !key) throw new Error("Server unavailable"); const response = await fetch(`${url.replace(/\/+$/, "")}/rest/v1/${path}`, { ...options, headers: { "Content-Type": "application/json", apikey: key, Authorization: `Bearer ${key}`, ...(options.headers || {}) } }); const raw = await response.text(); let data = null; try { data = raw ? JSON.parse(raw) : null; } catch {} if (!response.ok) { const error = new Error("Database request failed"); error.status = response.status; throw error; } return data; }

export default async function handler(req, res) {
  if (!["GET", "POST", "PATCH"].includes(req.method)) return res.status(405).json({ error: "Method not allowed" });
  const body = req.method === "GET" ? {} : parse(req.body); if (!body) return res.status(400).json({ error: "Invalid request body" });
  if (body.action === "accept") {
    if (req.method !== "POST" || Object.keys(body).some((field) => !["action", "invitation_id"].includes(field))) return res.status(400).json({ error: "Invalid invitation" });
    let auth; try { auth = await requireAuthenticatedUser(req); } catch (error) { return sendAuthError(res, error); }
    if (!auth.enforced || !uuid(body.invitation_id) || !auth.email) return res.status(400).json({ error: "Invalid invitation" });
    try { const rows = await request("rpc/accept_business_team_invitation", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify({ p_invitation_id: body.invitation_id, p_user_id: auth.userId, p_email: auth.email }) }); const accepted = Array.isArray(rows) ? rows[0] : rows; if (!accepted?.business_id) throw new Error("Database request failed"); await recordAuditEvent({ businessId: accepted.business_id, actorUserId: auth.userId, action: "team.invitation_accepted", resourceType: "team_invitation", resourceId: body.invitation_id, metadata: { role: accepted.role } }); return res.status(200).json({ accepted: true }); } catch { return res.status(400).json({ error: "Invitation is unavailable" }); }
  }
  let auth; try { auth = await requireBusinessMember(req, ["owner"]); } catch (error) { return sendAuthError(res, error); }
  if (!auth.enforced) return res.status(503).json({ error: "Team controls are not enabled" });
  try {
    if (req.method === "GET") { const [members, invitations] = await Promise.all([request(`business_memberships?business_id=eq.${encodeURIComponent(auth.businessId)}&select=user_id,role,created_at&order=created_at.asc`), request(`business_team_invitations?business_id=eq.${encodeURIComponent(auth.businessId)}&select=id,invited_email,role,status,expires_at,created_at&order=created_at.desc`)]); return res.status(200).json({ members: Array.isArray(members) ? members : [], invitations: Array.isArray(invitations) ? invitations : [] }); }
    if (req.method === "POST") { if (Object.keys(body).some((field) => !["email", "role"].includes(field))) return res.status(400).json({ error: "Invalid team invitation" }); const invitedEmail = email(body.email); const role = body.role; if (!invitedEmail || !["admin", "member"].includes(role)) return res.status(400).json({ error: "Invalid team invitation" }); const [members, invitations] = await Promise.all([request(`business_memberships?business_id=eq.${encodeURIComponent(auth.businessId)}&select=user_id`), request(`business_team_invitations?business_id=eq.${encodeURIComponent(auth.businessId)}&status=eq.pending&select=id`)]); await assertStaffSeatAvailable(auth.businessId, (Array.isArray(members) ? members.length : 0) + (Array.isArray(invitations) ? invitations.length : 0)); const rows = await request("business_team_invitations", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify({ business_id: auth.businessId, invited_email: invitedEmail, role, invited_by: auth.userId }) }); const invitation = Array.isArray(rows) ? rows[0] : rows; if (!invitation?.id) throw new Error("Database request failed"); await recordAuditEvent({ businessId: auth.businessId, actorUserId: auth.userId, action: "team.invited", resourceType: "team_invitation", resourceId: invitation.id, metadata: { role } }); return res.status(201).json({ id: invitation.id, role: invitation.role, expires_at: invitation.expires_at, accept_path: `/?invite=${encodeURIComponent(invitation.id)}` }); }
    if (Object.keys(body).some((field) => !["invitation_id", "status"].includes(field)) || !uuid(body.invitation_id) || body.status !== "revoked") return res.status(400).json({ error: "Invalid team invitation" }); const rows = await request(`business_team_invitations?id=eq.${encodeURIComponent(body.invitation_id)}&business_id=eq.${encodeURIComponent(auth.businessId)}&status=eq.pending`, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify({ status: "revoked", updated_at: new Date().toISOString() }) }); if (!Array.isArray(rows) || !rows[0]) return res.status(404).json({ error: "Invitation not found" }); await recordAuditEvent({ businessId: auth.businessId, actorUserId: auth.userId, action: "team.invitation_revoked", resourceType: "team_invitation", resourceId: body.invitation_id }); return res.status(200).json({ revoked: true });
  } catch (error) { if (error?.status === 409) return res.status(409).json({ error: error.message || "An active invitation already exists" }); if (error?.status === 402) return res.status(402).json({ error: error.message || "An active subscription is required" }); return res.status(500).json({ error: "Could not process team request" }); }
}
